# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Username')),
                ('require_valid_password', models.BooleanField(default=False, verbose_name='Require a Valid Password')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='Password')),
                ('pass_if_pw_match', models.BooleanField(default=True, verbose_name='Pass authentication if Password Match')),
            ],
        ),
    ]
